name: fairness-in-ml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipython
  - jedi
  - jupyter
  - keras
  - matplotlib
  - notebook
  - pandas
  - pip
  - python=3.6
  - scikit-learn
  - seaborn
  - pytorch